# Memory settings for the Gradle build process
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Parchment
neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17
neogradle.subsystems.conventions.runs.create-default-run-per-type=false

# NeoForge
neo_version=21.1.240
neo_version_range=[21.1.0,)
loader_version_range=[4,)
tag_lanzador=NeoForge

# Dependencies
jei_version=19.27.0.344
kubejs_version=2101.7.2-build.374
kubejs_version_range=[2101.7.2,)
rhino_version=2101.2.7-build.81
astralsorcery_curse_file=8985152
astralsorcery_version_range=[2.0.1,)
observerlib_version=1.10.3.31

## Mod Properties
minecraft_version=1.21.1
minecraft_version_range=1.21.1
mod_id=kubejsastralsorcery
mod_name=Astral Sorcery KJS
mod_named=AstralSorceryKJS
mod_license=GPL-3.0-only
mod_version=2101.1.0
mod_group_id=nadiendev.kubejsastralsorcery
mod_authors=NadienDev
mod_description=Full KubeJS support for Astral Sorcery. Create and remove every Astral Sorcery recipe from a script, register new constellations and altar tiers, add pages to the tome, and tweak lumen bindings, focal points and config values.
issue_tracker=https://github.com/SrNadien/KubeJS-Astral-Sorcery/issues
