AstralSorcery.registry('constellations', event => {
  event.create('kubejs:lyra')
    .displayName('Lyra')
    .subtitle('The Harp of the Night')
    .description('A constellation added by KubeJS.')
    .color('#7F5FFF')
    .major()
    .star(4, 5).star(12, 3).star(20, 9).star(26, 20).star(16, 27).star(6, 22)
    .chain(0, 1, 2, 3, 4, 5)
    .connect(5, 0)
    .focusCrystal('unique_distances')
    .focalPoint()
    .rootPerk('vicio', -45, 20)
    .rootPerkModifier('astralsorcery:movement_speed', 1, 0.05)
    .skyPosition(200, 45)

  event.create('kubejs:ferrum')
    .displayName('Ferrum')
    .color(0xAAAAAA)
    .minor()
    .stars([[3, 3], [28, 4], [15, 28]])
    .connections([[0, 1], [1, 2], [2, 0]])
    .moonPhases('full', 'new')
})
