AstralSorcery.recipes(event => {
  event.altar_crafting('minecraft:diamond', ['ABA', 'BCB', 'ABA'], {
    A: 'astralsorcery:aquamarine',
    B: '#c:ingots/iron',
    C: 'minecraft:coal_block'
  }).id('kubejs:example/altar_basic')

  event.altar_crafting('2x minecraft:emerald', ['A A', ' B ', 'A A'], { A: 'minecraft:gold_ingot', B: 'astralsorcery:resonating_gem' })
    .type('radiance')
    .relay(['R   R', '     ', '     ', '     ', 'R   R'])
    .define('R', 'astralsorcery:stardust')
    .constellation('aevitas')
    .shatterChance(0.1)
    .duration(300)
    .anyTime()
    .starlight('aevitas', 'astralsorcery:armara')
    .lumen('prismatic', 200)
    .fluid('astralsorcery:liquid_starlight', 1000)
    .additional('4x minecraft:redstone')
    .researchTier('radiance')
    .id('kubejs:example/altar_full')

  event.altar('minecraft:nether_star', ['AAA', 'ABA', 'AAA'], { A: 'minecraft:obsidian', B: { fluid: 'minecraft:lava', amount: 1000 } })
    .type('luminance')
    .replaceWithInput('grid', 4)
    .setComponent('minecraft:rarity', 'epic')
    .id('kubejs:example/altar_mapping_fluid_key')

  event.altar_crafting('minecraft:beacon', [' A ', 'ABA', ' A '], { A: 'minecraft:glass', B: 'minecraft:nether_star' })
    .type('resonance')
    .upgradesTo('minecraft:beacon')
    .noEffects()
    .effect('default_central_beam')
    .id('kubejs:example/altar_set_block')

  event.altar_crafting('minecraft:nether_star', ['GGG', 'GDG', 'GGG'], { G: 'minecraft:gold_ingot', D: 'minecraft:diamond' })
    .type('luminance')
    .altar('kubejs:celestial_altar')
    .anyTime()
    .id('kubejs:example/altar_exclusive')

  event.altar_crafting('minecraft:elytra', ['FFF', 'FDF', 'FFF'], { F: 'minecraft:feather', D: 'minecraft:diamond' })
    .type('stellar')
    .anyTime()
    .duration(40)
    .id('kubejs:example/altar_stellar')

  event.focal_combine('minecraft:blue_orchid', ['minecraft:poppy', 'minecraft:lapis_lazuli'])
    .constellation('vicio')
    .duration(400)
    .color('#3F9FFF')
    .id('kubejs:example/combine')

  event.combine(['minecraft:dirt', 'minecraft:sand'], 'minecraft:gravel')
    .input('minecraft:flint')
    .id('kubejs:example/combine_multi')

  event.focal_transmutation('minecraft:cake[bites=2]', 'minecraft:melon')
    .duration(1200)
    .focused(true)
    .id('kubejs:example/transmutation')

  event.focal_transmutation(['minecraft:diamond_ore', 'minecraft:coal_ore'], ['#minecraft:logs', 'minecraft:stone'])
    .constellation('evorsio')
    .state('minecraft:iron_ore', 3)
    .input('minecraft:granite')
    .color(0x55FF55)
    .id('kubejs:example/transmutation_weighted')

  event.lumen_generation('aevitas', 'minecraft:oak_sapling')
    .amount(3)
    .attemptMultiplier(2)
    .starlightConsumption(1.5)
    .shatterMultiplier(0.5)
    .id('kubejs:example/lumen')

  event.lumen('akasha', 'minecraft:nether_star')
    .combine('aevitas', 10)
    .combine('armara', 4)
    .id('kubejs:example/lumen_combo')

  event.lumen_crystallization('vicio', 'minecraft:feather')
    .lumenPerOperation(900)
    .shatterMultiplier(3)
    .id('kubejs:example/crystallization')

  event.lightwell('minecraft:water', 'minecraft:ice')
    .productionMultiplier(1.2)
    .shatterMultiplier(0.2)
    .color('#88CCFF')
    .id('kubejs:example/lightwell')

  event.infusion('minecraft:glowstone', 'minecraft:redstone_block')
    .duration(100)
    .consumptionChance(0.2)
    .chalice(false)
    .id('kubejs:example/infusion')

  event.infusion('minecraft:prismarine', 'minecraft:cobblestone')
    .fluid('minecraft:water')
    .id('kubejs:example/infusion_water')

  event.liquid_starlight('minecraft:amethyst_shard', '2x minecraft:quartz')
    .with('minecraft:glowstone_dust')
    .duration(40)
    .consumesLiquid(true)
    .id('kubejs:example/liquid_starlight_drop')

  event.liquid_starlight([], 'astralsorcery:lumen_crystal')
    .with('astralsorcery:stardust')
    .with({ type: 'astralsorcery:lumen_bindable' })
    .bindLumen()
    .consumesInputs(false)
    .id('kubejs:example/liquid_starlight_bind')

  event.liquid_interaction('minecraft:obsidian', Fluid.of('astralsorcery:liquid_starlight', 10), Fluid.of('minecraft:water', 10))
    .chanceA(0.3)
    .weight(5)
    .id('kubejs:example/interaction')

  event.liquid_interaction('minecraft:dirt', Fluid.of('minecraft:lava', 5), Fluid.of('minecraft:water', 5))
    .spawnEntity('minecraft:blaze')
    .id('kubejs:example/interaction_entity')

  event.remove({ id: 'astralsorcery:altar/illumination_wand' })
  event.remove({ altar_tier: 'radiance', output: 'astralsorcery:dynamism_gem_sky' })
  event.remove({ astral_type: 'lightwell', fluid: 'minecraft:lava' })
  event.remove({ constellation: 'discidia', astral_type: 'combine' })
  event.remove({ lumen: ['caldor', 'hyle'], astral_type: 'lumen' })
  event.remove({ output_block: 'minecraft:cake' })
  event.remove({ focus: 'armara' })
  event.remove({ research_tier: 'luminance' })
  event.remove([{ id: 'astralsorcery:infusion/glass_lens' }, { id: 'astralsorcery:infusion/resonating_gem' }])
  event.replaceInput({ id: 'astralsorcery:focal_combine/wand' }, 'astralsorcery:aquamarine', 'minecraft:emerald')
  event.replaceInput({ astral_type: 'altar', id: 'astralsorcery:altar/akashic_singularity_with_generated_artifact_loot' }, 'astralsorcery:stardust', 'minecraft:glowstone_dust')
})
